version: 2

project_name: dotsync

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: dotsync
    main: ./cmd/dotsync
    binary: dotsync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}

archives:
  - id: dotsync
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

dockers_v2:
  - ids:
      - dotsync
    images:
      - "ghcr.io/smykla-labs/dotsync"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/smykla-labs/.github"
      "org.opencontainers.image.description": "Organization sync tool for labels, files, and smyklot versions"
      "org.opencontainers.image.licenses": "MIT"
    extra_files:
      - LICENSE

release:
  github:
    owner: smykla-labs
    name: .github
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## dotsync {{ .Version }}

    Container images available at:
    - `ghcr.io/smykla-labs/dotsync:{{ .Version }}`
    - `ghcr.io/smykla-labs/dotsync:{{ .Major }}`
    - `ghcr.io/smykla-labs/dotsync:{{ .Major }}.{{ .Minor }}`
    - `ghcr.io/smykla-labs/dotsync:latest`
