---
extends: default

rules:
  # Allow inline comments with 1 space (for action version comments)
  comments:
    min-spaces-from-content: 1

  # GitHub Actions uses `on:` which is a truthy value
  truthy:
    allowed-values: ["true", "false", "on"]

  # Disable line length checks
  line-length: disable
