---
name: List Repositories (dotsync)
description: >-
  List organization repositories using dotsync container

inputs:
  token:
    description: GitHub token for API access
    required: true
  org:
    description: Organization name
    required: true
    default: smykla-labs
  format:
    description: Output format (json|names)
    required: false
    default: json

runs:
  using: docker
  image: docker://ghcr.io/smykla-labs/dotsync:latest
  args:
    - repos
    - list
    - --org=${{ inputs.org }}
    - --format=${{ inputs.format }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
