---
name: Get Repositories
description: >-
  Get repositories for sync operations. Returns single repo if specified,
  otherwise lists all repos via dotsync.

inputs:
  repo:
    description: "Single repository name (optional, lists all if not provided)"
    required: false
    default: ""
  token:
    description: "GitHub token (required when listing all repos)"
    required: false
    default: ""
  org:
    description: "Organization name (defaults to repository owner)"
    required: false
    default: ""

outputs:
  repos:
    description: "JSON array of repository objects [{name, full_name}]"
    value: ${{ steps.single.outputs.repos || steps.list.outputs.repos }}

runs:
  using: composite
  steps:
    - name: Use single repo from input
      id: single
      if: inputs.repo != ''
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo }}
        REPO_OWNER: ${{ inputs.org || github.repository_owner }}
      run: |
        echo "repos=$(jq -cn --arg name "$REPO_NAME" --arg owner "$REPO_OWNER" \
          '[{name: $name, full_name: ($owner + "/" + $name)}]')" >> "$GITHUB_OUTPUT"

    - name: List all repositories
      id: list
      if: inputs.repo == ''
      # Uses the root action.yml from this repository
      uses: ./
      with:
        command: repos
        subcommand: list
        token: ${{ inputs.token }}
